version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: Setup tmp directory and alias
          command: mkdir ~/tmp && cd ~/tmp && alias ll='ls -l'
      - run:
          name: Obtain node package
          command: curl -O 'https://nodejs.org/dist/v6.11.4/node-v6.11.4-linux-x64.tar.xz'
      - run:
          name: Extract the node package contents
          command: tar xfJ node-v6.11.4-linux-x64.tar.xz
      - run:
          name: Add the node bin to the PATH environment variable
          command: export PATH=$PATH:/home/circleci/tmp/node-v6.11.4-linux-x64/bin/
      - run:
          name: Install Appium
          command: npm install -g appium@1.6.5
      - run:
          name: Add the Java bin directory to the PATH environment variable
          command: export PATH=$PATH:$JAVA_HOME/bin
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Start the Appium server
          command: appium
          background: true
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Run Tests
          command: rspec 'test_spec.rb' --tag screenshot_tests
